### ISSUE TITLE
`correlation_id_filter` cannot be used in string based configurations

### ISSUE THREAD

**Issue by faph** [snok/asgi-correlation-id#32]
See https://docs.python.org/3/library/logging.config.html#user-defined-objects

The expected pattern in logging.config is to use strings for custom formatter, handler and filter classes. For example, in YAML, this would look like this:

```yaml
filters:
  correlation_id:
    (): asgi_correlation_id.correlation_id_filter
    uuid_length: 12
handlers:
  std_out:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
    filters:
      - correlation_id
```

This would be executed as Python `asgi_correlation_id.correlation_id_filter(uuid_length=12)`.

However, this should return an **instance** of `CorrelationId` instead of a class.

It seems that this `correlation_id_filter` factory function could be replaced by the class itself with `uuid_length` being an argument of `__init__()`?
